# Generated by Django 6.0.6 on 2026-06-16 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaMuseo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255, verbose_name='Nombre completo')),
                ('anios_experiencia_guia', models.IntegerField(verbose_name='Años de experiencia')),
                ('idiomas_hablados', models.CharField(max_length=255, verbose_name='Idiomas hablados')),
            ],
            options={
                'verbose_name': 'Guía de Museo',
                'verbose_name_plural': 'Guías de Museo',
            },
        ),
        migrations.CreateModel(
            name='Museo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
                ('ciudad', models.CharField(max_length=150, verbose_name='Ciudad')),
                ('anio_fundacion', models.IntegerField(verbose_name='Año de fundación')),
            ],
            options={
                'verbose_name': 'Museo',
                'verbose_name_plural': 'Museos',
            },
        ),
        migrations.CreateModel(
            name='Exhibicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_exhibicion', models.CharField(max_length=255, verbose_name='Título de la exhibición')),
                ('duracion_meses', models.IntegerField(verbose_name='Duración (meses)')),
                ('costo_produccion', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Costo de producción')),
                ('tematica', models.CharField(max_length=255, verbose_name='Temática')),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibiciones', to='institucion.guiamuseo', verbose_name='Guía de museo')),
            ],
            options={
                'verbose_name': 'Exhibición',
                'verbose_name_plural': 'Exhibiciones',
            },
        ),
        migrations.AddField(
            model_name='guiamuseo',
            name='museo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guias', to='institucion.museo', verbose_name='Museo'),
        ),
    ]
